BEGIN TRANSACTION;

DROP TABLE IF EXISTS `TB_Memory`;
DROP TABLE IF EXISTS `TB_Cpu`;
DROP TABLE IF EXISTS `TB_Battery`;

CREATE TABLE IF NOT EXISTS `TB_Memory` (
    `Id`         INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    `usage`      INTEGER,
    `total`      INTEGER,
    `date`       REAL
);
CREATE TABLE IF NOT EXISTS `TB_Cpu` (
    `ID`         INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    `usage`      INTEGER,
    `date`       REAL
);
CREATE TABLE IF NOT EXISTS `TB_Battery` (
    `Id`         INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    `remaining`  INTEGER,
    `date`       REAL
);
COMMIT;
